export enum textTypes {
    TITLE_BOLD = 'TITLE_BOLD',
    TITLE_LIGHT = 'TITLE_LIGHT',
    TITLE_REGULAR = 'TITLE_REGULAR',
    TITLE_SEMI_BOLD = 'TITLE_SEMI_BOLD',

    SUB_TITLE_BOLD = 'SUB_TITLE_BOLD',
    SUB_TITLE_LIGHT = 'SUB_TITLE_LIGHT',
    SUB_TITLE_REGULAR = 'SUB_TITLE_REGULAR',
    SUB_TITLE_SEMI_BOLD = 'SUB_TITLE_SEMI_BOLD',
    
    BUTTON_BOLD = ' BUTTON_BOLD',
    BUTTON_LIGHT = 'BUTTON_LIGHT',
    BUTTON_REGULAR = 'BUTTON_REGULAR',
    BUTTON_SEMI_BOLD = ' BUTTTON_SEMI_BOLD',

    PARAGRAPH_BOLD = 'PARAGRAPH_BOLD',
    PARAGRAPH_LIGHT = 'PARAGRAPH_LIGHT',
    PARAGRAPH_REGULAR = 'PARAGRAPH_REGULAR',
    PARAGRAPH_SEMI_BOLD = 'PARAGRAPH_SEMI_BOLD',

    PARAGRAPH_SMALL_BOLD = 'PARAGRAPH_SMALL_BOLD',
    PARAGRAPH_SMALL_LIGHT = 'PARAGRAPH_SMALL_LIGHT',
    PARAGRAPH_SMALL_REGULAR = 'PARAGRAPH_SMALL_REGULAR',
    PARAGRAPH_SMALL_SEMI_BOLD = 'PARAGRAPH_SMALL_SEMI_BOLD',
}   